image:
  file: .gitpod.Dockerfile

ports:
  - port: 3000
    onOpen: ignore
  - port: 3035
    onOpen: ignore
  - port: 5432
    onOpen: ignore
  - port: 6379
    onOpen: ignore
  - port: 9200
    onOpen: ignore
  - port: 9300
    onOpen: ignore

tasks:
  - name: Forecast Server
    before: |
      redis-server &
    init: >
      cp .env.example .env && gem install solargraph && gem install bundler && bin/setup
    command: >
      bin/startup
  - command: >
      gp await-port 3000 && printf "Waiting for Forecast server ..." && until
      $(curl -sNL $(gp url 3000) | grep -q "html"); do printf '.'; sleep 5; done
      && echo "" && gp preview $(gp url 3000)
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
# enable for all branches in this repo (defaults to false)
    branches: true
# enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
# enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: false
# add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
# add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false
# add a check to pull requests (defaults to true)
    addCheck: true

vscode:
  extensions:
    - rebornix.ruby@0.28.0:6jqvDzl/avsj94yYXFjzQw==
    - wingrunr21.vscode-ruby@0.27.0:beIqQUhLRuJ5Vao4B2Lyng==