language: ruby
cache:
  - bundler
  - yarn
services:
  - postgresql
before_install:
  - nvm install 14
  - gem install bundler:2.2.5
before_script:
  - bundle install --jobs=3 --retry=3
  - yarn
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
script:
  - bundle exec rake test
  - bundle exec rake test:system